[package]
name = "x86_vlapic"
version = "0.1.0"
edition = "2024"
description = "x86 Virtual Local APIC"

[dependencies]
log = "0.4.19"
paste = "1.0.15"
tock-registers = "0.9.0"
bit = "0.1.1"

memory_addr = "0.3"
axerrno = "0.1.0"

axaddrspace = { git = "https://github.com/arceos-hypervisor/axaddrspace.git" }
axdevice_base = { git = "https://github.com/arceos-hypervisor/axdevice_crates.git" }

axvisor_api = { git = "https://github.com/arceos-hypervisor/axvisor_api.git" }
